- package.json
- routes/azureSpecials.js
Before this change, the server was sending `"OK"` (string OK) response and this fails `JSON.parse()` deserialization in the TS runtime. 
- Fixing it to match the swagger spec.
> We need to send a 200 response back not a response with string OK as the response body.

- package.json
- startup/shutdown.js
- startup/www.js
With this script one can "npm stop" to terminate the test HTTP server.
It works by using a local socket as an RPC mechanism.  When the server
starts it will open a socket listening for message "npmStop" which when
received will terminate the test server process.  The stop script will
send the "npmStop" message.
> Add stop script for cross-plat termination of HTTP server.

- package.json
- swagger/body-complex.json
- swagger/extensible-enums-swagger.json
Reverts Azure/autorest.testserver#35
Reverting since this breaks regeneration tests in all generator/modeler repos (have to publish AutoRest as well/first to unblock those!)
> Revert "Removing modelAsExtensible"

- startup/shutdown.js
Ensure that the stop script terminates; if this doesn't happen the node
process can linger and end up stopping the test server when it starts.
> Fix stop script.

- .vscode/launch.json
- app.js
- package.json
- Uses an OS-agnostic path separator in launch.json
- Adds the cors middleware package which lets us do browser testing in autorest.typescript
> Enable CORS. Fix path separator in launch.json

- swagger/xml-service.json
@fearthecowboy @RikkiGibson This is what we discussed, Swagger does not allow having $ref and XML/Name at the same time, and we should not support it.
That's an easy fix that is completely iso-functional and will generate exactly the same thing, but following Swagger recommendation :). There is already enough trouble with the XML spec in Swagger, to create ourselves more trouble with invalid syntax ;)
Note that we must update the official Storage Swagger for DataPlane with that, and I would be surprised that anyone has a trouble with that, the message is really "Please update this way, that's the same thing, but at least it's valid Swagger". I didn't find this spec on the RestAPI specs repo, I don't what Go guys are using to generate the SDK.
> Remove mixed ref and xml/name

- routes/lros.js
The swagger defines ID as string but the test server was returning an
integer which breaks Go.  Changed return type to string to match.
> Make ID payload data type match the swagger definition.

- package.json
- routes/xml.js
This was actually in the Swagger but I somehow never created the route for it. This is meant to exercise custom response headers and case insensitivity to make sure there are no bad interactions with the XML code paths in each language runtime. There's no actual XML sent or received.
> Add endpoint for XML headers method

- .npmignore
- package.json
The package for 2.5.18 was over 100 MB uncompressed because my local test results were all included in the package.. Let's not do that.
> Don't publish test results

- package.json
- swagger/xml-service.json
This actually turned out to not be many places where we still used this way. Banana here has an xml name on the model definition already.
> Remove remaining property xml names

- package.json
- routes/xml.js
This gracefully handles the XML parse failure by responding with 400 instead of hanging.
> Xml parse failure

- app.js
- package.json
- routes/additionalProperties.js
- swagger/additionalProperties.json
Adds test case for [de]serializing a subclass of a class with additionalProperties. This helps us test a case which currently doesn't work in node SDK according to user reports (related to graph IIRC)
> Add AdditionalPropertiesSubclass fixture

- package.json
- routes/complex.js
- swagger/body-complex.json
Java deserialization was failing when it handles json string containing polymorphic object but without discriminator, in such cases deserializer should use the type specified in the model.
Test ensure this case is validated for both scalar and vector properties of a model.
> Test for type that composes polymorphic object without explicit discriminator

- app.js
- coverage/coverageEndpoint.js
- package.json
I'm setting up test infrastructure where we would start a server run a test and verify that it hit the expected endpoint. I need a way to query current coverage.
@lmazuel @fearthecowboy @MiYanni
> Add an endpoint to get the current coverage results

- package.json
- swagger/required-optional.json
For these operations, when implemented as tests, SDK should fail the client side validation and no calls should be done. The Swagger has been designed as a "All status code are failure" to try to represent that, which is unrealistic, and doesn't match any real life endpoint. This is adding 200 as ok scenario in order for code to generate something that makes sense.
Note that if the client-side validation doesn't work and the call is made, SDK will receive a 404, so the test will still receive an error from the server anyway. So doesn't change the actual behavior.
> Add a success to all RequiredOptional

- legacy/routes/paths.js
- package.json
- swagger/url.json
According to https://tools.ietf.org/html/rfc3986#appendix-A, any "pchar" is acceptable as the not-encoded form in the Swagger path.
Adding a test for that, since we got an issue with the Swagger of Storage tables that contains a single quote https://github.com/Azure/autorest.python/issues/242
> Add not-encoded authorized characters

- legacy/routes/errorStatusCodes.js
- package.json
XMS Error Swagger declares to produce JSON, so all routes should return valid JSON (or no body) otherwise the test doesn't make sense.
> Fix xms-response JSON return

- legacy/routes/datetime.js
- package.json
Current version doesn't allow `0001-01-01T10:00:00.000Z`
> Fix date comparison to allow ISO 8601 format

- legacy/routes/datetime.js
- package.json
Made a mistake in 2.10.0 about coverage of `getDateTimeMaxUtc7MSUppercase`
> Fix coverage report

- legacy/routes/additionalProperties.js
- legacy/routes/array.js
- legacy/routes/azureUrl.js
- legacy/routes/bool.js
- legacy/routes/byte.js
- legacy/routes/complex.js
- legacy/routes/date.js
- legacy/routes/datetime-rfc1123.js
- legacy/routes/datetime.js
- legacy/routes/dictionary.js
- legacy/routes/duration.js
- legacy/routes/errorStatusCodes.js
- legacy/routes/extensibleEnums.js
- legacy/routes/httpResponses.js
- legacy/routes/int.js
- legacy/routes/lros.js
- legacy/routes/model-flatten.js
- legacy/routes/number.js
- legacy/routes/paging.js
- legacy/routes/report.js
- legacy/routes/reqopt.js
- legacy/routes/string.js
- legacy/routes/validation.js
- legacy/routes/xml.js
- package.json
Current testserver doesn't set Content-Type at all, and there is several problems with that:
- If our runtime might use this information, we don't test that (Python does use it, and we have a special hack for the testserver...)
- Wiremock recordings don't know it's readable, so [saves the recording as base64](https://github.com/Azure/autorest.testserver/blob/f88f537120cfc2b1927bdb0f2aede5eaa140a028/mappings/azure/paging_multiple_page_2-0e479f5b-81a9-4dce-8d75-c295e745106f.json#L10), which makes the recording impossible to read and update (like updating the absolute link of paging to use "baseUrl" @MiYanni )
That's a cumbersome work, but I think it's necessary. Anyone feel free to participate :)
> Add JSON Content-Type to tests

- legacy/app.js
- legacy/util/utils.js
- package.json
In .net we start the test server on a random port. Support this scenario by getting port from express instead of env variable.
> Allow for dynamic port in paging tests

- legacy/coverage/coverage.js
This should unblock https://github.com/Azure/autorest.python/pull/492 so that a GitHub token isn't needed to publish coverage results.
> Allow skipping GitHub comment in coverage run if token is "skip"

- legacy/coverage/coverage.js
- package.json
This change fixes some relative paths that were invalidated with the move of code coverage scripts into the `legacy` folder.  Needed to unblock https://github.com/Azure/autorest.python/pull/492
> Fix relative paths used for checking package versions

- swagger/body-string.json
Removing null and empty string enums from body string group.
> Removing invalid enums in body-string swagger

- legacy/coverage/app-immediate-push.js
- legacy/coverage/cli.js
- legacy/coverage/coverage.js
- package.json
Allow specifying a generator version when publishing test server
coverage.  If no version is specified, use previous behavior.
> Add optional version param to coverage commands

- legacy/app.js
- package.json
It doesn't server any purpose, since this is declared in the formData file itself, and broke 2.10.23....
> Remove pre-declaration of FormData tests

- legacy/routes/paging.js
- package.json
- swagger/paging.json
Adds required coverage 'PagingMultipleWithQueryParameters'. 
To pass, you need to first pass '100' to `requiredQueryParameter`. `getWithQueryParams` has constant `queryConstant` defined to be true and that must make it's way to the testserver. The query parameter `queryConstant` (and only `queryConstant`) then needs to be passed correctly to the next operation `nextOperationWithQueryParams` to finally pass 'PagingMultipleWithQueryParameters'
> Add paging operation with query params

- legacy/routes/lros.js
- package.json
Having `Location` causes a final GET to occur, which returns 202, which is outside of ARM spec:
https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/Addendum.md#call-action-post-asynchronously
> Fix LROsCustomHeader_postAsyncRetrySucceeded

- legacy/routes/mediatypes.js
- package.json
- swagger/media_types.json
This adds required coverage 'MediaTypeWithEncoding'. To pass it, pass contentType 'text/plain; encoding=UTF-8' (I haven't made input value required, should this be?)
> added test for content type with encoding

- legacy/routes/lros.js
- package.json
- swagger/lro.json
See: https://github.com/Azure/autorest.csharp/issues/743
Basically, for PUT specifically, an ARM resource can succeed on the initial call, and return a 201 status code. This test is specifically for `Resources_CreateOrUpdate` in the resources RP, where this can happen.
> LRO: PUT 201 successful test

- package.json
- swagger/body-datetime.json
- swagger/url.json
There's certain swaggers that have the meaning of "description" and "summary" flipped, so I flipped those back
> switched summary and description in some swaggers

- legacy/routes/paging.js
- package.json
- swagger/paging.json
fixes #182 
Added require coverage 'PagingReturnModelWithXMSClientName'. 
The test involves generating an operation, which returns a paging model whose item name has an x-ms-client-name.
> Added paging test for model whose item name has x-ms-client-name

- swagger/body-string.json
The description of the operation states base-64 encoded however the
format was incorrectly set to base-64 URL encoded.  In addition, the
route sends a base-64 encoded value.
> Fix formatting of string_getBase64Encoded response

- package.json
Ended up not bumping the package version in my query array test PR since someone merged a PR before me and I didn't bump the package version again from that. My apologies
> bump version for query array test

- package.json
- swagger/body-formdata.json
This adds a new operation called 'uploadfiles' to the `body-formdata.json` spec which exercises the case where a `formData` parameter has an array of `file` items to enable uploading multiple files in one API call.  I haven't added the backend support for this yet, would appreciate some pointers on that!
> Add a body-formdata operation that accepts an array of files

- package.json
- swagger/xms-error-responses.json
This PR is related to Issue https://github.com/Azure/autorest.typescript/issues/749. 
Currently, the inheritance is not defined correctly in the JSON File. 
1. Take a look [here](https://github.com/Azure/autorest.testserver/blob/ee473a350ebd680a728acda7d3bbd4334e9826a0/legacy/routes/errorStatusCodes.js#L59). This returns the object `hungryScooby`. 
2. The definition of `hungryScooby` is:
```
{
"actionResponse":"howl",
"errorType":"PetHungryOrThirstyError",
"errorMessage":"scooby is low",
"reason":"need more everything",
"hungryOrThirsty":"hungry and thirsty"
}
```
The `actionResponse` property is defined only in PetAction. Else, TS will start complaining.
This PR will fix it. 
@joheredi Please review and approve.
> Fix the inheritance of xms error codes json

- legacy/routes/paging.js
- package.json
- swagger/paging.json
> add test for first page no items, second page with items

- legacy/app.js
- legacy/routes/errorStatusCodes.js
- package.json
- swagger/xms-error-responses.json
Python ran into an issue for (error) model deserialization when our operation had an input parameter named `models`. 
(python [ex](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/digitaltwins/azure-digitaltwins-core/azure/digitaltwins/core/_generated/operations/_digital_twin_models_operations.py#L121)). Adding test to make sure other languages don't run into this conflict. Making this optional coverage, since right now it seems p specific to how python deserializes models. Other languages shouldn't have a problem passing the test though
> add test for error deserialization in op with param name 'models'

- .scripts/start-autorest-express.js
- package.json
This change updates the `start-autorest-express` script so that the exit code of the program it wraps will be used as this script's own exit code when it exits.  This fixes an issue that was causing the AutoRest Swift repo's CI to report success even though there were errors while running its tests.
> Pass through program exit code when using start-autorest-express

- package.json
- src/test-routes/incorrect-error-response.ts
- swagger/incorrect-error-response.json
Python has an [issue](https://github.com/Azure/autorest.python/issues/791) where, in the case of failed error model deserialization, we still want to return an `HttpResponseError` to users, not a deserialization error. This is a test that throws an incorrect error model, that should result in a deserialization error. Ideally, your autorest code should throw an `HttpResponseError` instead of a `DeserializationError`
> add test for error deserialization

- .azure-pipelines/ci.yml
- src/app/app.ts
- src/cli/args-parser.ts
- src/cli/cli-config.ts
- src/cli/cli.ts
- src/cli/commands/index.ts
- src/cli/commands/validate-spec-coverage-command.ts
- src/legacy/legacy.ts
- src/services/index.ts
- src/services/spec-coverage-service.ts
New comand to validate missing apis
```bash
autorest-testserver validate-spec-coverage
```
Current `--help`:
```bash
PS C:\dev\azsdk\autorest.megarepo\testserver> autorest-testserver --help
cli.js
Run the autorest test server.
Commands:
cli.js                         Run the autorest test server.         [default]
cli.js stop                    Stop the autorest test server running at the
provided port.
cli.js validate-spec-coverage  Validate there is a mock api for all the path
defined in the specs
Options:
--version            Show version number                         [boolean]
--help               Show help                                   [boolean]
-v, --verbose            Run with verbose logging level.             [boolean]
--debug              Run with debug logging level. …
```
> Feature: Add a new command to validate coverage of openapi specs

- docs/writing-mock-apis.md
- package.json
- src/api/index.ts
- src/api/mock-request.ts
- src/api/request-expectation.ts
- src/test-routes/lro/test.ts
- src/test-routes/required-optional-params/binary-body-required-optional.ts
- src/test-routes/required-optional-params/body-required-optional.ts
- src/test-routes/required-optional-params/general-require-optional.ts
- src/test-routes/string.ts
- src/test-routes/xml-service.ts
A change on how to use the built-in request validation tools. All expectation are now under `req.expect` instead of directly under `req`. This makes it more obvious what is going to be a expecting a result vs just getting a value.
> Scope request validation

- package.json
- src/test-routes/formdata.ts
- swagger/body-formdata-urlencoded.json
- Changes generated code to something closer to our expectation
- https://gist.github.com/chamons/54eb354a28cceb1558379c6ba5664fcf
- Also  Remove status from expected body as it is optional, and we're no longer unconditionally sending
> Add modelAsString to url encoding test

- package.json
- swagger/multiapi-v0.json
Currently all of the multiapi operation versions all have mixin operations. Recently found a regression in multiapi versions without mixins, so adding this test.
> add multiapi version no mixins

- package.json
- swagger/additionalProperties.json
The track 1 modeler didn't correctly interpret the schema definition,
and now that we fixed the behavior in track 2 the codegen doesn't match
what the route expects.
Fix the schema definition to match the route and not break tests.
> Fix PetAPObject schema definition to match route

- .azure-pipelines/ci.yml
- .gitignore
- package-lock.json
- package.json
Seems like the express types library updated to add typings to parameters using string literal(Parsing from the path) but this has a flaw currently with optional params.
Also un ignore package-lock.json so dev package don't get updated like that
> Fix regression in types library

- package.json
fix #294
Shouldn't need to run npm run build on install. `prepublish` is also deprecated https://docs.npmjs.com/cli/v7/using-npm/scripts
> Change prepublish to prepack

- package.json
- swagger/azure-special-properties.json
- swagger/body-boolean.json
- swagger/body-date.json
- swagger/body-datetime-rfc1123.json
- swagger/body-datetime.json
- swagger/body-number.json
- swagger/body-string.json
- swagger/complex-model.json
- swagger/httpInfrastructure.json
- swagger/paging.json
- swagger/url.json
- swagger/validation.json
- swagger/xml-service.json
Previous modelers made the assumption that single-value enums were
constant values which lead to some inconsistencies.
Update swaggers where the intent was to treat the enums as constants.
> Explicitly declare single-value enums as constants

- legacy/routes/mediatypes.js
- package.json
- swagger/media_types.json
This way the value can be used verbatim when forming the request.
> Be explicit in the consumes media type value

- legacy/routes/lros.js
- package.json
- swagger/lro.json
Add two lro patch method tests to verify the Lro logic in .Net SDK. One will contain Azure-AsyncOperation header and another contains both Azure-AsyncOperation and Location Header.
> Add two tests for lro patch method

- src/api/mock-api-router.ts
- src/test-routes/dpg/update.ts
- swagger/dpg_initial.json
- swagger/dpg_update1.json
DPG Service Evolution swaggers contained a couple of routes that had no actual routes in the TestServer. This PR implements the missing routes.
- `app.head("/servicedriven/parameters", "DPGAddOptionalInput_NoParams")`
- ` app.put("/servicedriven/parameters", "DPGAddOptionalInput_RequiredOptionalParam")`
- `app.get("/serviceDriven/moreParameters", "DPGAddOptionalInput_OptionalParam")`
- `app.get("/servicedriven/glassbreaker", "DPGGlassBreaker")`
> Implement missing routes from DPG swaggers

- package.json
- src/services/coverage-service.ts
fix #345
While investigating autorest.go's disappointing testserver coverage, I observed that written coverage reports always record 0 hits for legacy routes. Turns out legacy hits are tracked but not written to disk. Here's a quick fix for that. I'm not familiar with the architecture here, so please let me know if you prefer a different fix.
> Save legacy route coverage

- legacy/routes/paging.js
- package.json
The path - ` paging/multiple/nextOperationWithQueryParams` with api-version will return 400
Request: http://localhost:3000/paging/multiple/nextOperationWithQueryParams?queryConstant=true&api-version=1.0.0
Response: error: Error The query parameters to nextOperationWithQueryParams were not passed correctly {"status":400}
info: GET /paging/multiple/nextOperationWithQueryParams?queryConstant=true&api-version=1.0.0 400 1.006 ms – 105
Below two paths are accepted after fixing it:
•	Without api-version:
Request: http://localhost:3000/paging/multiple/nextOperationWithQueryParams?queryConstant=true
Response: info: info: GET /paging/multiple/nextOperationWithQueryParams?queryConstant=true 200 13.812 ms - 53
•	With api-version:
Request: http://localhost:3000/paging/multiple/nextOperationWithQueryPar …
> Accept api-version parameter in path - paging/multiple/nextOperationWithQueryParams

- swagger/body-string.json
Update from https://github.com/Azure/autorest.testserver/pull/381
> Fix copy-paste error in the `x-ms-examples` values for body-string.json

- package.json
Bump a new version to deliver the security fixed to downstream packages.
For example, `autorest.csharp` imports `autorest.testserver`: https://github.com/Azure/autorest.csharp/blob/68e44c384b4809bb4c1e989571ba19f081c3ff48/package.json#L19
> build: bump version to 3.3.50

- package.json
Fixes #427
The express package need to be bumped to address a security vulnerability in ``path-to-regexp`` package. Please refer to the PR over here https://github.com/expressjs/express/pull/6209
> Bump express package from 4.17.2 to 4.21.2
