- app.js
- package.json
- routes/complex.js
- swagger/body-complex.json
new coverage test for missing discriminators while serializing and deserializing
> Added new swagger and route for missing discriminator scenario

- package.json
- routes/extensibleEnums.js
Fix https://github.com/Azure/autorest/issues/2788
With help of @amarzavery :)
FYI @dsgouda
> Fix extensibleEnum incorrect content-type

- routes/lros.js
Updating tests used by LRO.
Added a way to honor Location header in addition to Async-operation header for POST/Delete requests.
The diff shown below is incorrect. All I did was changed few lines and added one additional function.
> fixing lro tests

- swagger/body-complex.json
Swagger update for bug https://github.com/Azure/autorest/issues/2899
Swagger made by @amarzavery 
There is not HTTP tests, since generating is enough to reproduce the bug (invalid Python). We don't know if  this bug impacts more than NodeJS or Python.
Tell me if you want an explicit request and a coverage test
> Swagger update for bug 2889

- package.json
- routes/lros.js
- swagger/lro.json
- Add new operation postFinalLocationGet in LROS
- Should poll and get a Product object
- Id should be the string "100"
> Add POST LRO with final GET on Location test

- package.json
- routes/lros.js
- swagger/lro.json
Add a new test that represents te default behavior should backward compatible and poll AzureAsyncOp
> Default LRO

- package.json
- routes/xml.js
- swagger/xml-service.json
FYI @RikkiGibson @rickle-msft 
Testing it for Python before merging.
Related to https://github.com/Azure/autorest.java/issues/264
> Add complex type ref complex type tests

- app.js
- package.json
- routes/array.js
- swagger/body-array.json
We didn't have an actual test for enum arrays before. This got us in trouble in typescript so I feel there should be a test case for this moving forward.
Note that a lot of the +/- lines here is just reformatting body-array.json in 15f1cab. I suggest just looking at the subsequent commits 237027b, aee9acd, 561cc31.
> Enum array

- package.json
- routes/xml.js
- swagger/xml-service.json
XML tests are NOT the right place to discuss weird date parsing issues.
If we want to play with how many digits should we support, etc. there is a date file for that (and we should by the way, but not the point of this PR).
> Xml date simplification

- app.js
- package.json
- routes/xml.js
- swagger/xml-service.json
In a Swagger that is mostly XML, having _one_ operation that takes JSON as input.
> Json xml test

- legacy/app.js
- legacy/coverage/coverageEndpoint.js
- legacy/routes/report.js
- package.json
- swagger/report.json
- Add azure in coverageEndpoint
- Add optional in report
> Complete coverage report

- legacy/app.js
- legacy/startup/www.js
- package.json
I think I was double binding before.
> Try the port change again but better

- swagger/body-byte.json
Remove constants in respose schemas.
Fix Error schema to match what's returned.
> Cleanup the body-byte.json swagger

- swagger/body-complex.json
This PR adds the ApiVersionParameter to the basic_getValid endpoint and also updates the enum value for the ApiVersionParameter field.
> Updating endpoint basic_getValid to include APIVersionParameter

- legacy/coverage/coverage.js
- package.json
> Make sure coverage "immediate push" script will upload the blob

- legacy/app.js
- legacy/routes/objectType.js
- package.json
- swagger/object-type.json
> added basic type:object testing

- package.json
- swagger/xml-service.json
It's not being sent back https://github.com/Azure/autorest.testserver/blob/master/legacy/routes/xml.js#L86
> Remove required property from XML test

- legacy/routes/lros.js
- package.json
The call to actually return the result is missing for this LRO test.
> LRO test fix

- legacy/app.js
- legacy/routes/azureSpecials.js
- legacy/routes/nonStringEnums.js
- package.json
- swagger/non-string-enum.json
> added non string enum test

- legacy/app.js
- legacy/routes/time.js
- package.json
- swagger/body-time.json
fixes #152 
```
>>> res = requests.get("http://localhost:3000/time/get")
>>> res.text
'"11:34:56"'
>>> res =  requests.put("http://localhost:3000/time/put", json="08:07:56")
>>> res.text
'"Nice job posting time"'
```
> added BodyTime test case

- legacy/routes/array.js
- legacy/routes/complex.js
- legacy/routes/dictionary.js
- legacy/routes/xml.js
- legacy/util/utils.js
- package.json
body-date already allowed dates like `2009-09-29T08:49:37.1230000+00:00` only string based tests didn't.
> Allow other ISO compatible date formats

- legacy/routes/datetime.js
- package.json
- swagger/body-datetime.json
EventHubs RM sends a value like this.
> Add min-date-nooffset test

- legacy/app.js
- package.json
Fixes - https://github.com/Azure/autorest.testserver/issues/191
For more info see - https://github.com/Azure/autorest.csharp/issues/821#event-3449820379
> Fix race condition when creating TestResults directory

- swagger/body-boolean.json
- swagger/examples/bool_getTrue.json
- swagger/examples/bool_putTrue.json
Add examples in swagger for cli
> Add init example for cli codegen in test service

- swagger/constants.json
- swagger/generate_constants_swagger.py
> Add constant Swagger

- package.json
- swagger/subscriptionId-apiVersion.json
Please review and approve. 
@daviwil @joheredi Please review and approve
@ramya-rao-a FYI....
> Fix host value in subscription id and api version json

- legacy/routes/queries.js
- package.json
If test empty, then since this is multi, this means no query parameters at all
> Fix queries multi

- swagger/body-dictionary.json
The addition helps generating more precise types.
> [body-dictionary] adding x-nullable to ops that return null

- swagger/body-binary-json
Add a new sample taking care of the case where the body content type is json but it's a file.
> Add body-binary-json.json sample

- package.json
- swagger/extensible-enums-swagger.json
> add long description for an enum value to test wrapping

- package.json
- src/server/server.ts
Fix is logging the actual selected port.
> Support passing port 0 to select random port

- package.json
- src/routes/coverage.ts
Incorrectly defined `GET /report/clear` instead of `POST /report/clear`
> Fix /report/clear method(GET -> POST)

- .editorconfig
- .vscode/extensions.json
- README.md
Add vscode recommended extension list + update docs
> Document recommended extensions

- .eslintrc.yml
Adding this rule which as an auto fix
https://eslint.org/docs/rules/eqeqeq
> Add eqeqeq eslint rule

- package.json
- src/api/request-expectation.ts
- src/api/request-validations.ts
- src/test-routes/formdata.ts
- swagger/body-formdata-urlencoded.json
- Part of https://github.com/azure/autorest.csharp/issues/986
- .NET test that will land later - https://gist.github.com/chamons/76c377098cb30e2dc8b6214ebf3326f2
> [test] Add urlencoded form

- package.json
- src/api/request-expectation.ts
- src/test-routes/formdata.ts
- swagger/body-formdata-urlencoded.json
@chamons i'm makign the test optional coverage for now since the autorest core change needed for this to work hasn't been merged yet
> make some changes to test, and make optional for now

- src/test-routes/any-type.ts
- swagger/any-type.json
Added spec and test server implementation
> Added spec for Anything type.

- package.json
Latest version of wiremock seems to have an issue installing
> Fix version of wiremock

- package.json
- src/test-routes/reserved-words.ts
- swagger/reserved-words.json
this PR just adds operation groups with reserved words, but leaves the door open for others in the future
> add reserved words tests

- package.json
- swagger/body-string.quirks.json
Missing change in body-string-quirks.json from #309
> Fix body string quirks enums

- package-lock.json
- package.json
- swagger/body-number.quirks.json
- swagger/httpInfrastructure.quirks.json
> Fix more single value enums

- package.json
- swagger/xms-error-responses.json
Bump version number for next release.
> Add missing port number to host

- swagger/llc_initial.json
- swagger/llc_update1.json
@lmazuel, for your consideration.
This adds variants to test adding an optional parameter to different combinations of parameter lists for C#.
> Add required/optional test variants to LLC tests

- package.json
- swagger/paging.json
> Fix: `"null"` instead of `null` in paging.json spec

- .prettierignore
- legacy/routes/formData.js
- package-lock.json
- package.json
previous pr bumping busboy introduced breaking changes https://github.com/Azure/autorest.testserver/pull/384
> Fix busboy breaking changes

- package-lock.json
- swagger/body-string.json
- swagger/dpg-customization.json
- swagger/examples/getModel.json
- swagger/examples/lro.json
- swagger/examples/nextLink.json
- swagger/examples/postModel.json
Add examples in body-string swagger file
issue here: https://github.com/Azure/autorest.typescript/issues/1389
> Adding examples in body-string swagger file

- package-lock.json
- package.json
- src/reporter/coverage.ts
Should resolve the vulnerability issue with reference to md5.js https://devdiv.visualstudio.com/DevDiv/_componentGovernance/117532/alert/6445111?typeId=7802694
> Use @azure/storage-blob instead of deprecated azure-storage

- legacy/routes/paging.js
- package.json
- swagger/paging.json
add pageable scenario for python : https://github.com/Azure/autorest.python/issues/1408
> Paging with body

- legacy/routes/paging.js
- package.json
- swagger/paging.json
Fix https://github.com/Azure/autorest.testserver/pull/402
> Fix paging with body

- package-lock.json
- package.json
- bump ts-jest to latest version
- bump jest to latest version to resolve version conflict with ts-jest
- bump version to 3.3.48
resolve #420
> build(library): bump ts-jest to latest version

- .azure-pipelines/ci.yml
- .azure-pipelines/publish.yml
- .azure-pipelines/steps/build-test.yml
Moved build and test steps into a template file.
> Add publish pipeline config
